// Auto-generated by sdkgen
import { ContractFactory, ContractRunner } from "quantumcoin";
import { IERC20 } from "./IERC20";
import type * as Types from "./types";

export declare class IERC20__factory extends ContractFactory {
  constructor(runner: ContractRunner);
  deploy(overrides?: any): Promise<IERC20>;
  static connect(address: string, runner?: ContractRunner): IERC20;
}
