// Auto-generated by sdkgen
import { ContractFactory, ContractRunner } from "quantumcoin";
import { QuantumSwapV2Pair } from "./QuantumSwapV2Pair";
import type * as Types from "./types";

export declare class QuantumSwapV2Pair__factory extends ContractFactory {
  constructor(runner: ContractRunner);
  deploy(overrides?: any): Promise<QuantumSwapV2Pair>;
  static connect(address: string, runner?: ContractRunner): QuantumSwapV2Pair;
}
