// Auto-generated by sdkgen
import { ContractFactory, ContractRunner } from "quantumcoin";
import { QuantumSwapV2Factory } from "./QuantumSwapV2Factory";
import type * as Types from "./types";

export declare class QuantumSwapV2Factory__factory extends ContractFactory {
  constructor(runner: ContractRunner);
  deploy(_feeToSetter: Types.AddressLike, overrides?: any): Promise<QuantumSwapV2Factory>;
  static connect(address: string, runner?: ContractRunner): QuantumSwapV2Factory;
}
