// Auto-generated by sdkgen
import { Contract, ContractRunner, ContractTransactionResponse, TransactionResponse } from "quantumcoin";
import type * as Types from "./types";

export declare class QuantumSwapV2Factory extends Contract {
  static readonly abi: readonly any[];
  static readonly bytecode: string;
  static connect(address: string, runner?: ContractRunner): QuantumSwapV2Factory;
  constructor(address: string, runner?: ContractRunner, _deployTx?: TransactionResponse);
  readonly populateTransaction: {
    createPair(tokenA: Types.AddressLike, tokenB: Types.AddressLike, overrides?: any): Promise<import("quantumcoin").TransactionRequest>;
    setFeeTo(_feeTo: Types.AddressLike, overrides?: any): Promise<import("quantumcoin").TransactionRequest>;
    setFeeToSetter(_feeToSetter: Types.AddressLike, overrides?: any): Promise<import("quantumcoin").TransactionRequest>;
  };
  INIT_CODE_HASH(): Promise<Types.Bytes32>;
  allPairs(arg0: Types.Uint256Like): Promise<Types.SolAddress>;
  allPairsLength(): Promise<Types.Uint256>;
  createPair(tokenA: Types.AddressLike, tokenB: Types.AddressLike, overrides?: any): Promise<ContractTransactionResponse>;
  feeTo(): Promise<Types.SolAddress>;
  feeToSetter(): Promise<Types.SolAddress>;
  getPair(arg0: Types.AddressLike, arg1: Types.AddressLike): Promise<Types.SolAddress>;
  setFeeTo(_feeTo: Types.AddressLike, overrides?: any): Promise<ContractTransactionResponse>;
  setFeeToSetter(_feeToSetter: Types.AddressLike, overrides?: any): Promise<ContractTransactionResponse>;
}
