// Auto-generated by sdkgen
import { Contract, ContractRunner, ContractTransactionResponse, TransactionResponse } from "quantumcoin";
import type * as Types from "./types";

export declare class QuantumSwapV2ERC20 extends Contract {
  static readonly abi: readonly any[];
  static readonly bytecode: string;
  static connect(address: string, runner?: ContractRunner): QuantumSwapV2ERC20;
  constructor(address: string, runner?: ContractRunner, _deployTx?: TransactionResponse);
  readonly populateTransaction: {
    approve(spender: Types.AddressLike, value: Types.Uint256Like, overrides?: any): Promise<import("quantumcoin").TransactionRequest>;
    transfer(to: Types.AddressLike, value: Types.Uint256Like, overrides?: any): Promise<import("quantumcoin").TransactionRequest>;
    transferFrom(from: Types.AddressLike, to: Types.AddressLike, value: Types.Uint256Like, overrides?: any): Promise<import("quantumcoin").TransactionRequest>;
  };
  allowance(arg0: Types.AddressLike, arg1: Types.AddressLike): Promise<Types.Uint256>;
  approve(spender: Types.AddressLike, value: Types.Uint256Like, overrides?: any): Promise<ContractTransactionResponse>;
  balanceOf(arg0: Types.AddressLike): Promise<Types.Uint256>;
  decimals(): Promise<Types.Uint8>;
  name(): Promise<string>;
  symbol(): Promise<string>;
  totalSupply(): Promise<Types.Uint256>;
  transfer(to: Types.AddressLike, value: Types.Uint256Like, overrides?: any): Promise<ContractTransactionResponse>;
  transferFrom(from: Types.AddressLike, to: Types.AddressLike, value: Types.Uint256Like, overrides?: any): Promise<ContractTransactionResponse>;
}
