// Auto-generated by sdkgen
import { Contract, ContractRunner, ContractTransactionResponse, TransactionResponse } from "quantumcoin";
import type * as Types from "./types";

export declare class QuantumSwapV2Router02 extends Contract {
  static readonly abi: readonly any[];
  static readonly bytecode: string;
  static connect(address: string, runner?: ContractRunner): QuantumSwapV2Router02;
  constructor(address: string, runner?: ContractRunner, _deployTx?: TransactionResponse);
  readonly populateTransaction: {
    addLiquidity(tokenA: Types.AddressLike, tokenB: Types.AddressLike, amountADesired: Types.Uint256Like, amountBDesired: Types.Uint256Like, amountAMin: Types.Uint256Like, amountBMin: Types.Uint256Like, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<import("quantumcoin").TransactionRequest>;
    addLiquidityETH(token: Types.AddressLike, amountTokenDesired: Types.Uint256Like, amountTokenMin: Types.Uint256Like, amountETHMin: Types.Uint256Like, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<import("quantumcoin").TransactionRequest>;
    removeLiquidity(tokenA: Types.AddressLike, tokenB: Types.AddressLike, liquidity: Types.Uint256Like, amountAMin: Types.Uint256Like, amountBMin: Types.Uint256Like, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<import("quantumcoin").TransactionRequest>;
    removeLiquidityETH(token: Types.AddressLike, liquidity: Types.Uint256Like, amountTokenMin: Types.Uint256Like, amountETHMin: Types.Uint256Like, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<import("quantumcoin").TransactionRequest>;
    removeLiquidityETHSupportingFeeOnTransferTokens(token: Types.AddressLike, liquidity: Types.Uint256Like, amountTokenMin: Types.Uint256Like, amountETHMin: Types.Uint256Like, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<import("quantumcoin").TransactionRequest>;
    swapETHForExactTokens(amountOut: Types.Uint256Like, path: Types.SolArray<Types.AddressLike>, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<import("quantumcoin").TransactionRequest>;
    swapExactETHForTokens(amountOutMin: Types.Uint256Like, path: Types.SolArray<Types.AddressLike>, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<import("quantumcoin").TransactionRequest>;
    swapExactETHForTokensSupportingFeeOnTransferTokens(amountOutMin: Types.Uint256Like, path: Types.SolArray<Types.AddressLike>, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<import("quantumcoin").TransactionRequest>;
    swapExactTokensForETH(amountIn: Types.Uint256Like, amountOutMin: Types.Uint256Like, path: Types.SolArray<Types.AddressLike>, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<import("quantumcoin").TransactionRequest>;
    swapExactTokensForETHSupportingFeeOnTransferTokens(amountIn: Types.Uint256Like, amountOutMin: Types.Uint256Like, path: Types.SolArray<Types.AddressLike>, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<import("quantumcoin").TransactionRequest>;
    swapExactTokensForTokens(amountIn: Types.Uint256Like, amountOutMin: Types.Uint256Like, path: Types.SolArray<Types.AddressLike>, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<import("quantumcoin").TransactionRequest>;
    swapExactTokensForTokensSupportingFeeOnTransferTokens(amountIn: Types.Uint256Like, amountOutMin: Types.Uint256Like, path: Types.SolArray<Types.AddressLike>, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<import("quantumcoin").TransactionRequest>;
    swapTokensForExactETH(amountOut: Types.Uint256Like, amountInMax: Types.Uint256Like, path: Types.SolArray<Types.AddressLike>, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<import("quantumcoin").TransactionRequest>;
    swapTokensForExactTokens(amountOut: Types.Uint256Like, amountInMax: Types.Uint256Like, path: Types.SolArray<Types.AddressLike>, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<import("quantumcoin").TransactionRequest>;
  };
  WETH(): Promise<Types.SolAddress>;
  addLiquidity(tokenA: Types.AddressLike, tokenB: Types.AddressLike, amountADesired: Types.Uint256Like, amountBDesired: Types.Uint256Like, amountAMin: Types.Uint256Like, amountBMin: Types.Uint256Like, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<ContractTransactionResponse>;
  addLiquidityETH(token: Types.AddressLike, amountTokenDesired: Types.Uint256Like, amountTokenMin: Types.Uint256Like, amountETHMin: Types.Uint256Like, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<ContractTransactionResponse>;
  factory(): Promise<Types.SolAddress>;
  getAmountIn(amountOut: Types.Uint256Like, reserveIn: Types.Uint256Like, reserveOut: Types.Uint256Like): Promise<Types.Uint256>;
  getAmountOut(amountIn: Types.Uint256Like, reserveIn: Types.Uint256Like, reserveOut: Types.Uint256Like): Promise<Types.Uint256>;
  getAmountsIn(amountOut: Types.Uint256Like, path: Types.SolArray<Types.AddressLike>): Promise<Types.SolArray<Types.Uint256>>;
  getAmountsOut(amountIn: Types.Uint256Like, path: Types.SolArray<Types.AddressLike>): Promise<Types.SolArray<Types.Uint256>>;
  quote(amountA: Types.Uint256Like, reserveA: Types.Uint256Like, reserveB: Types.Uint256Like): Promise<Types.Uint256>;
  removeLiquidity(tokenA: Types.AddressLike, tokenB: Types.AddressLike, liquidity: Types.Uint256Like, amountAMin: Types.Uint256Like, amountBMin: Types.Uint256Like, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<ContractTransactionResponse>;
  removeLiquidityETH(token: Types.AddressLike, liquidity: Types.Uint256Like, amountTokenMin: Types.Uint256Like, amountETHMin: Types.Uint256Like, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<ContractTransactionResponse>;
  removeLiquidityETHSupportingFeeOnTransferTokens(token: Types.AddressLike, liquidity: Types.Uint256Like, amountTokenMin: Types.Uint256Like, amountETHMin: Types.Uint256Like, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<ContractTransactionResponse>;
  swapETHForExactTokens(amountOut: Types.Uint256Like, path: Types.SolArray<Types.AddressLike>, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<ContractTransactionResponse>;
  swapExactETHForTokens(amountOutMin: Types.Uint256Like, path: Types.SolArray<Types.AddressLike>, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<ContractTransactionResponse>;
  swapExactETHForTokensSupportingFeeOnTransferTokens(amountOutMin: Types.Uint256Like, path: Types.SolArray<Types.AddressLike>, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<ContractTransactionResponse>;
  swapExactTokensForETH(amountIn: Types.Uint256Like, amountOutMin: Types.Uint256Like, path: Types.SolArray<Types.AddressLike>, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<ContractTransactionResponse>;
  swapExactTokensForETHSupportingFeeOnTransferTokens(amountIn: Types.Uint256Like, amountOutMin: Types.Uint256Like, path: Types.SolArray<Types.AddressLike>, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<ContractTransactionResponse>;
  swapExactTokensForTokens(amountIn: Types.Uint256Like, amountOutMin: Types.Uint256Like, path: Types.SolArray<Types.AddressLike>, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<ContractTransactionResponse>;
  swapExactTokensForTokensSupportingFeeOnTransferTokens(amountIn: Types.Uint256Like, amountOutMin: Types.Uint256Like, path: Types.SolArray<Types.AddressLike>, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<ContractTransactionResponse>;
  swapTokensForExactETH(amountOut: Types.Uint256Like, amountInMax: Types.Uint256Like, path: Types.SolArray<Types.AddressLike>, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<ContractTransactionResponse>;
  swapTokensForExactTokens(amountOut: Types.Uint256Like, amountInMax: Types.Uint256Like, path: Types.SolArray<Types.AddressLike>, to: Types.AddressLike, deadline: Types.Uint256Like, overrides?: any): Promise<ContractTransactionResponse>;
}
