// Auto-generated by sdkgen
import { ContractFactory, ContractRunner } from "quantumcoin";
import { QuantumSwapV2Router02 } from "./QuantumSwapV2Router02";
import type * as Types from "./types";

export declare class QuantumSwapV2Router02__factory extends ContractFactory {
  constructor(runner: ContractRunner);
  deploy(_factory: Types.AddressLike, _WETH: Types.AddressLike, overrides?: any): Promise<QuantumSwapV2Router02>;
  static connect(address: string, runner?: ContractRunner): QuantumSwapV2Router02;
}
