// Auto-generated by sdkgen
import { ContractFactory, ContractRunner } from "quantumcoin";
import { QuantumSwapV2ERC20 } from "./QuantumSwapV2ERC20";
import type * as Types from "./types";

export declare class QuantumSwapV2ERC20__factory extends ContractFactory {
  constructor(runner: ContractRunner);
  deploy(overrides?: any): Promise<QuantumSwapV2ERC20>;
  static connect(address: string, runner?: ContractRunner): QuantumSwapV2ERC20;
}
