// Auto-generated by sdkgen
import { Contract, ContractRunner, ContractTransactionResponse, TransactionResponse } from "quantumcoin";
import type * as Types from "./types";

export declare class WQ extends Contract {
  static readonly abi: readonly any[];
  static readonly bytecode: string;
  static connect(address: string, runner?: ContractRunner): WQ;
  constructor(address: string, runner?: ContractRunner, _deployTx?: TransactionResponse);
  readonly populateTransaction: {
    approve(guy: Types.AddressLike, wad: Types.Uint256Like, overrides?: any): Promise<import("quantumcoin").TransactionRequest>;
    deposit(overrides?: any): Promise<import("quantumcoin").TransactionRequest>;
    transfer(dst: Types.AddressLike, wad: Types.Uint256Like, overrides?: any): Promise<import("quantumcoin").TransactionRequest>;
    transferFrom(src: Types.AddressLike, dst: Types.AddressLike, wad: Types.Uint256Like, overrides?: any): Promise<import("quantumcoin").TransactionRequest>;
    withdraw(wad: Types.Uint256Like, overrides?: any): Promise<import("quantumcoin").TransactionRequest>;
  };
  allowance(arg0: Types.AddressLike, arg1: Types.AddressLike): Promise<Types.Uint256>;
  approve(guy: Types.AddressLike, wad: Types.Uint256Like, overrides?: any): Promise<ContractTransactionResponse>;
  balanceOf(arg0: Types.AddressLike): Promise<Types.Uint256>;
  decimals(): Promise<Types.Uint8>;
  deposit(overrides?: any): Promise<ContractTransactionResponse>;
  name(): Promise<string>;
  symbol(): Promise<string>;
  totalSupply(): Promise<Types.Uint256>;
  transfer(dst: Types.AddressLike, wad: Types.Uint256Like, overrides?: any): Promise<ContractTransactionResponse>;
  transferFrom(src: Types.AddressLike, dst: Types.AddressLike, wad: Types.Uint256Like, overrides?: any): Promise<ContractTransactionResponse>;
  withdraw(wad: Types.Uint256Like, overrides?: any): Promise<ContractTransactionResponse>;
}
