// Auto-generated by sdkgen
import { ContractFactory, ContractRunner } from "quantumcoin";
import { WQ } from "./WQ";
import type * as Types from "./types";

export declare class WQ__factory extends ContractFactory {
  constructor(runner: ContractRunner);
  deploy(overrides?: any): Promise<WQ>;
  static connect(address: string, runner?: ContractRunner): WQ;
}
